### ISSUE TITLE
IVoiceInterface

### ISSUE THREAD

**Issue by Ed-warf** [jalc96/audio_recorder_unreal_engine#1]
You probably need to include a module in the build.cs to support that.
Usually when you see that sth does not want to compile it is because you don't added the module to the build system.
In this case you should add "Voice" module to PrivateDependencyModuleNames. The name of module can usually be found in the docs. But you can easily deduce it from the path where file is located in the form ..../module_name/private/file.cpp

**Comment by jalc96** [comment]
Thank you, this is fixed now `FVoiceModule::Get().CreateVoiceCapture("");` doesn't create the `IVoiceCapture` object, I'm investigating that.
